// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUPbmKqcMEMfsQ2RC20JNEiZMcYJWcPPg',
    appId: '1:363711052423:android:efaf0599669784c0459622',
    messagingSenderId: '363711052423',
    projectId: 'ceremonial-buddha',
    storageBucket: 'ceremonial-buddha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJyzT3C7j4ndxpeGtNFyidVIWc3NGub3Q',
    appId: '1:363711052423:ios:85d2eb1447a348cb459622',
    messagingSenderId: '363711052423',
    projectId: 'ceremonial-buddha',
    storageBucket: 'ceremonial-buddha.appspot.com',
    iosClientId: '536317961776-feumorfhq2p1rm6rb8noqn77m4c9af7n.apps.googleusercontent.com',
    iosBundleId: 'com.aquarious.ceremonialbuddha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYyr1JaSTroyuQXcqrj_kyuVI8_lwUWYo',
    appId: '1:536317961776:ios:1494720ca04806446c2ff5',
    messagingSenderId: '536317961776',
    projectId: 'stayats-930d1',
    storageBucket: 'stayats-930d1.appspot.com',
    iosClientId: '536317961776-feumorfhq2p1rm6rb8noqn77m4c9af7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.stayats',
  );
}
